@authToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjY3MzI0OTE5LCJleHAiOjE2Njk5MTY5MTl9.YCPwxq6ts_C5MXz5phBiHlEJP5g3MsvkyAm8phadWjM

@host=http://localhost:1337
###

POST {{host}}/api/auth/local
content-type: application/json

{"identifier": "testuser","password":"testuser"}


###

GET {{host}}/api/icon

###

GET {{host}}/uploads/Arrow_east_d39befddfe.svg


###

GET {{host}}/api/upload/files/12
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

GET {{host}}/uploads/Antoni_Wilinski_AI_2bd84edf61.png
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

POST {{host}}/api/clients
Content-Type: application/json
# Authorization: Bearer {{authToken}}

{"data":{"username":"tedasdadastdatysu"}}

###

GET {{host}}/api/clients?populate=*
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

POST {{host}}/api/products?populate=*
Content-Type: application/json
Authorization: Bearer {{authToken}}

{"data":{
    "name": "vzjvczsdaddadadaasdadax",
    "codeName": "danmn,m",
    "category": "koszulka",
    "desc": "dsnm,da",
    "color": {
        "colorName": "Biały",
        "colorHex": "#ffffff"
    },
    "iconId": 3,
    "previewImg": {
        "id": 96,
        "name": "error.svg",
        "alternativeText": null,
        "caption": null,
        "width": null,
        "height": null,
        "formats": null,
        "hash": "error_9b9e5c9235",
        "ext": ".svg",
        "mime": "image/svg+xml",
        "size": 0.62,
        "url": "/uploads/error_9b9e5c9235.svg",
        "previewUrl": null,
        "provider": "local",
        "provider_metadata": null,
        "createdAt": "2022-04-21T13:22:39.848Z",
        "updatedAt": "2022-04-21T13:22:39.848Z"
        
    }

}}

###

POST {{host}}/api/products
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "data": {
        "name": "fdkddasfjksadkajkf",
        "codeName": "",
        "category": "koszulka",
        "desc": "",
        "color": {
            "colorName": "Biały",
            "colorHex": "#ffffff"
        },
        "iconId": null
    }
}



###

PUT {{host}}/api/upload/public/1
Content-Type: application/json
Authorization: Bearer {{authToken}}

{"public":true}

###

GET {{host}}/api/upload/files/68
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

GET {{host}}/api/upload/download/305
Content-Type: application/json
Authorization: Bearer {{authToken}}


###

GET {{host}}/api/upload/download/317?token=KUf5xP4Ub2KJjTXupyuUPpL7KV10Lf-4MXtNAR7tAy6tF6bd
# Content-Type: application/json
# Authorization: Bearer {{authToken}}

###

PUT {{host}}/api/users-permissions/setWelcomeMessageHash
Content-Type: application/json
Authorization: Bearer {{authToken}}

{"welcomeMessageHash": "123"}

###

GET {{host}}/api/products/1
Content-Type: application/json
Authorization: Bearer {{authToken}}
